# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0002_footersnippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, verbose_name='Подзаголовок'),
        ),
    ]
