# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-07 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0003_performance_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSnippenSocialButton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('slug', models.SlugField(max_length=25, unique=True, verbose_name='Вид соцсети')),
                ('link', models.URLField(blank=True, verbose_name='Адрес сообщества')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='footersnippet',
            options={'verbose_name': 'Футер', 'verbose_name_plural': 'Футеры'},
        ),
        migrations.AddField(
            model_name='footersnippet',
            name='copyright',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Текст копирайта'),
        ),
        migrations.AddField(
            model_name='footersnippet',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Электропочта'),
        ),
        migrations.AddField(
            model_name='footersnippet',
            name='slug',
            field=models.SlugField(default='default', max_length=10, unique=True, verbose_name='Код'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footersnippet',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='footersnippensocialbutton',
            name='snippet',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_buttons', to='theatre.FooterSnippet'),
        ),
    ]
