# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-12 20:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0004_auto_20160807_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeEmbedSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=512, verbose_name='Название видео')),
                ('video_id', models.CharField(max_length=32, verbose_name='Код видео')),
                ('is_widescreen', models.BooleanField(default=True, help_text='Если включено - 16:9, если нет - 4:3', verbose_name='Широкоформатное видео')),
                ('autoplay', models.BooleanField(default=False, verbose_name='Автовоспроизведение')),
                ('loop', models.BooleanField(default=False, verbose_name='Зациклить видео')),
                ('fs', models.BooleanField(default=True, verbose_name='Разрешить показывать на весь экран')),
                ('rel', models.BooleanField(default=False, verbose_name='Показывать связанные видео')),
                ('player_end', models.PositiveIntegerField(blank=True, help_text='Воспроизведение остановится на указанной секунде. Оставьте пустым, чтобы воспроизвести видео целиком', null=True, verbose_name='Остановиться на')),
                ('player_start', models.PositiveIntegerField(blank=True, help_text='Воспроизведение начнется на указанной секунде. Оставьте пустым, чтобы воспроизвести видео целиком', null=True, verbose_name='Начать с')),
                ('player_playlist', models.CharField(blank=True, help_text='Дополнительные коды через запятую. Будут воспроизведены после основного видео', max_length=1024, verbose_name='Дополнительные видео')),
                ('player_listType', models.CharField(blank=True, choices=[('playlist', 'Плей-лист'), ('search', 'Поисковый запрос'), ('user_uploads', 'Все видео пользователя')], help_text='Выбрать, если используется плей-лист', max_length=12, verbose_name='Тип плейлиста')),
                ('player_list', models.CharField(blank=True, help_text='Указать, если используется плей-лист YouTube', max_length=32, verbose_name='Код плейлиста')),
            ],
            options={
                'verbose_name': 'Видео с YouTube',
            },
        ),
        migrations.AddField(
            model_name='performance',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='theatre.YouTubeEmbedSnippet', verbose_name='Видео с YouTube'),
        ),
    ]
