# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
        ('theatre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='performance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows_scheduled', to='theatre.Performance', verbose_name='Спектакль'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows_scheduled', to='theatre.Place', verbose_name='Площадка'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservations.Schedule', verbose_name='Показ'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='spectator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.Spectator', verbose_name='Зритель'),
        ),
    ]
