# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-24 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20160819_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spectator',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='spectator',
        ),
        migrations.AddField(
            model_name='reservation',
            name='children',
            field=models.TextField(blank=True, help_text='Укажите возраст и имена детей', verbose_name='Дополнительные сведения'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.EmailField(default='spectator@mail.ru', max_length=256, verbose_name='E-mail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='tel',
            field=models.CharField(blank=True, max_length=50, verbose_name='Мобильный телефон'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Стоимость основного билета'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='price_adult',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Стоимость доп. билета (взр)'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='price_child',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Стоимость доп. билета (детск)'),
        ),
        migrations.DeleteModel(
            name='Spectator',
        ),
    ]
