# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_auto_20160924_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='children',
        ),
    ]
